/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TictactoeRouteImport } from './routes/tictactoe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TictactoeUiRouteImport } from './routes/tictactoe/ui'

const TictactoeRoute = TictactoeRouteImport.update({
  id: '/tictactoe',
  path: '/tictactoe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TictactoeUiRoute = TictactoeUiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => TictactoeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tictactoe': typeof TictactoeRouteWithChildren
  '/tictactoe/ui': typeof TictactoeUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tictactoe': typeof TictactoeRouteWithChildren
  '/tictactoe/ui': typeof TictactoeUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tictactoe': typeof TictactoeRouteWithChildren
  '/tictactoe/ui': typeof TictactoeUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tictactoe' | '/tictactoe/ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tictactoe' | '/tictactoe/ui'
  id: '__root__' | '/' | '/tictactoe' | '/tictactoe/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TictactoeRoute: typeof TictactoeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tictactoe': {
      id: '/tictactoe'
      path: '/tictactoe'
      fullPath: '/tictactoe'
      preLoaderRoute: typeof TictactoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tictactoe/ui': {
      id: '/tictactoe/ui'
      path: '/ui'
      fullPath: '/tictactoe/ui'
      preLoaderRoute: typeof TictactoeUiRouteImport
      parentRoute: typeof TictactoeRoute
    }
  }
}

interface TictactoeRouteChildren {
  TictactoeUiRoute: typeof TictactoeUiRoute
}

const TictactoeRouteChildren: TictactoeRouteChildren = {
  TictactoeUiRoute: TictactoeUiRoute,
}

const TictactoeRouteWithChildren = TictactoeRoute._addFileChildren(
  TictactoeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TictactoeRoute: TictactoeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
