/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime=false ./cloudflare-env.d.ts` (hash: b34d01d0a8c4a2f2a647412e35b7b128)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
